CREATE TABLE IF NOT EXISTS players (
	id_player SMALLSERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	number INTEGER NOT NULL,
	position VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS staff (
	id_staff SMALLSERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	function VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS pointsGame (
	id_points_game SMALLSERIAL NOT NULL PRIMARY KEY,
	id_player SMALLSERIAL NOT NULL,
	number_points INTEGER NOT NULL,
	game VARCHAR (200) NOT NULL,
	season VARCHAR (50) NOT NULL,
	championship VARCHAR (200) NOT NULL,
	FOREIGN KEY(id_player) REFERENCES players(id_player)
);
