CREATE TABLE IF NOT EXISTS players (
	id_player SMALLSERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	number INTEGER NOT NULL,
	position VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS staff (
	id_staff SMALLSERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	function VARCHAR(30) NOT NULL
);
